[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
ndarray = "0.16.1"
neural-network = { path = "../neural-network" }
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = { version = "1.41.0", features = ["full"] }
